[package]
name = "jp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
itertools = "0.13"
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1"
